
package org.neogroup.sparks.processors.crud.datasource;

import org.neogroup.sparks.model.*;
import org.neogroup.sparks.processors.crud.CRUDProcessor;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

public abstract class DataSourceCRUDProcessor<E extends Entity> extends CRUDProcessor<E> {

    private final DataSource source;
    private EntityTableMetadata modelTableMetadata;

    public DataSourceCRUDProcessor() {
        this.source = createDataSource();
        this.modelTableMetadata = getResourceTableMetadata (entityClass);
    }

    protected DataSource getDataSource () {
        return source;
    }

    protected EntityTableMetadata getEntityTableMetadata() {
        return modelTableMetadata;
    }

    @Override
    protected E create(E entity, Map<String, Object> params) {

        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            int parameterIndex;
            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("INSERT INTO ");
            sql.append(modelTableMetadata.getTableName());
            sql.append(" (");

            parameterIndex = 1;
            for (EntityColumnMetadata columnMetadata : modelTableMetadata.getColumnMetadatas()) {
                if (!columnMetadata.isAutoGenerated()) {
                    if (parameterIndex > 1) {
                        sql.append(",");
                    }
                    sql.append(columnMetadata.getColumnName());
                    parameterIndex++;
                }
            }
            sql.append(") VALUES (");
            parameterIndex = 1;
            for (EntityColumnMetadata columnMetadata : modelTableMetadata.getColumnMetadatas()) {
                if (!columnMetadata.isAutoGenerated()) {
                    if (parameterIndex > 1) {
                        sql.append(",");
                    }
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(entity));
                    parameterIndex++;
                }
            }
            sql.append(")");

            PreparedStatement statement = connection.prepareStatement(sql.toString(), Statement.RETURN_GENERATED_KEYS);

            parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            int affectedRows = statement.executeUpdate();

            if (affectedRows != 0) {
                parameterIndex = 1;
                try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                    for (EntityColumnMetadata columnMetadata : modelTableMetadata.getColumnMetadatas()) {
                        if (columnMetadata.isAutoGenerated()) {
                            if (generatedKeys.next()) {
                                columnMetadata.getField().set(entity, generatedKeys.getObject(parameterIndex++));
                            } else {
                                throw new SQLException("Expecting generated value");
                            }
                        }
                    }
                }
            }
        }
        catch (Exception ex) {
            throw new RuntimeException ("Error creating entity", ex);
        }
        return entity;
    }

    @Override
    protected E update(E entity, Map<String, Object> params) {

        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            int parameterIndex;
            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("UPDATE ");
            sql.append(modelTableMetadata.getTableName());
            sql.append(" SET ");
            parameterIndex = 1;
            for (EntityColumnMetadata columnMetadata : modelTableMetadata.getColumnMetadatas()) {
                if (!columnMetadata.isId()) {
                    if (parameterIndex > 1) {
                        sql.append(",");
                    }
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(entity));
                    parameterIndex++;
                }
            }
            sql.append(" WHERE ");
            parameterIndex = 1;
            for (EntityColumnMetadata columnMetadata : modelTableMetadata.getColumnMetadatas()) {
                if (columnMetadata.isId()) {
                    if (parameterIndex > 1) {
                        sql.append(" AND ");
                    }
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(entity));
                    parameterIndex++;
                }
            }

            PreparedStatement statement = connection.prepareStatement(sql.toString());

            parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            int affectedRows = statement.executeUpdate();
        }
        catch (Exception ex) {
            throw new RuntimeException("Error updating entity", ex);
        }

        return entity;
    }

    @Override
    protected E delete(E entity, Map<String, Object> params) {

        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            int parameterIndex;
            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("DELETE FROM ");
            sql.append(modelTableMetadata.getTableName());
            sql.append(" WHERE ");
            parameterIndex = 1;
            for (EntityColumnMetadata columnMetadata : modelTableMetadata.getColumnMetadatas()) {
                if (columnMetadata.isId()) {
                    if (parameterIndex > 1) {
                        sql.append(" AND ");
                    }
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(entity));
                    parameterIndex++;
                }
            }

            PreparedStatement statement = connection.prepareStatement(sql.toString());
            parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            int affectedRows = statement.executeUpdate();
        }
        catch (Exception ex) {
            throw new RuntimeException("Error deleting entity", ex);
        }

        return entity;
    }

    @Override
    protected List<E> retrieve(EntityQuery query, Map<String, Object> params) {

        List<E> resources = new ArrayList<>();
        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("SELECT * FROM ");
            sql.append(modelTableMetadata.getTableName());

            if (!query.getFilters().isEmpty()) {
                sql.append(" WHERE ");
                buildFilterSQL(query.getFilters(), sql, sqlParameters);
            }

            if (!query.getSorters().isEmpty()) {
                sql.append(" ORDER BY ");
                Iterator<EntitySorter> orderIterator = query.getSorters().iterator();
                while (orderIterator.hasNext()) {
                    EntitySorter order = orderIterator.next();
                    EntityColumnMetadata columnMetadata = modelTableMetadata.getColumnMetadataByPropertyName(order.getProperty());
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" ");
                    switch (order.getDirection()) {
                        case ASC:
                            sql.append("ASC");
                            break;
                        case DESC:
                            sql.append("DESC");
                            break;
                    }
                    if (orderIterator.hasNext()) {
                        sql.append(",");
                    }
                }
            }

            if (query.getStart() != null) {
                sql.append(" START ");
                sql.append(query.getStart());
            }
            if (query.getLimit() != null) {
                sql.append(" LIMIT ");
                sql.append(query.getLimit());
            }

            PreparedStatement statement = connection.prepareStatement(sql.toString());
            int parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                E resource = createResourceFromResultSet(resultSet);
                resources.add(resource);
            }
        }
        catch (Exception ex) {
            throw new RuntimeException("Error retrieving entities", ex);
        }

        return resources;
    }

    private void buildFilterSQL(EntityFilter filter, StringBuilder sql, List<Object> sqlParameters) {

        if (filter instanceof EntityFilterGroup) {
            EntityFilterGroup resourceFilterGroup = (EntityFilterGroup)filter;
            sql.append("(");
            Iterator<EntityFilter> resourceFilterIterator = resourceFilterGroup.getFilters().iterator();
            while (resourceFilterIterator.hasNext()) {
                EntityFilter childEntityFilter = resourceFilterIterator.next();
                buildFilterSQL(childEntityFilter, sql, sqlParameters);

                if (resourceFilterIterator.hasNext()) {
                    switch (resourceFilterGroup.getConnector()) {
                        case AND:
                            sql.append(" AND ");
                            break;
                        case OR:
                            sql.append(" OR ");
                            break;
                    }
                }
            }
            sql.append(")");
        }
        else if (filter instanceof EntityPropertyFilter) {
            EntityPropertyFilter resourcePropertyFilter = (EntityPropertyFilter)filter;
            EntityColumnMetadata columnMetadata = modelTableMetadata.getColumnMetadataByPropertyName(resourcePropertyFilter.getProperty());
            switch (resourcePropertyFilter.getOperator()) {
                case EntityPropertyOperator.EQUALS:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case EntityPropertyOperator.DISTINCT:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("!=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case EntityPropertyOperator.GREATER_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(">");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case EntityPropertyOperator.GREATER_OR_EQUALS_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(">=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case EntityPropertyOperator.LESS_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("<");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case EntityPropertyOperator.LESS_OR_EQUALS_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("<=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case EntityPropertyOperator.CONTAINS:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" LIKE ");
                    sql.append("?");
                    sqlParameters.add("%" + resourcePropertyFilter.getValue() + "%");
                    break;
                case EntityPropertyOperator.NOT_CONTAINS:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" NOT LIKE ");
                    sql.append("?");
                    sqlParameters.add("%" + resourcePropertyFilter.getValue() + "%");
                    break;
                case EntityPropertyOperator.IN: {
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" IN ");
                    sql.append("(");
                    Collection valueCollection = (Collection) resourcePropertyFilter.getValue();
                    Iterator valueCollectionIterator = valueCollection.iterator();
                    while (valueCollectionIterator.hasNext()) {
                        Object singleValue = valueCollectionIterator.next();
                        sql.append("?");
                        sqlParameters.add(singleValue);
                        if (valueCollectionIterator.hasNext()) {
                            sql.append(",");
                        }
                    }
                    sql.append(")");
                    break;
                }
                case EntityPropertyOperator.NOT_IN: {
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" NOT IN ");
                    sql.append("(");
                    Collection valueCollection = (Collection) resourcePropertyFilter.getValue();
                    Iterator valueCollectionIterator = valueCollection.iterator();
                    while (valueCollectionIterator.hasNext()) {
                        Object singleValue = valueCollectionIterator.next();
                        sql.append("?");
                        sqlParameters.add(singleValue);
                        if (valueCollectionIterator.hasNext()) {
                            sql.append(",");
                        }
                    }
                    sql.append(")");
                    break;
                }
            }
        }
    }

    protected EntityTableMetadata getResourceTableMetadata (Class<? extends E> resourceClass) {
        return null;
    }

    protected E createResourceFromResultSet (ResultSet resultSet) {
        return null;
    }

    protected abstract DataSource createDataSource();
}
