
package org.neogroup.sparks.processors.crud.datasource;

import java.lang.reflect.Field;

public class EntityColumnMetadata {

    private final Field field;
    private final String columnName;
    private final boolean id;
    private final boolean autoGenerated;

    public EntityColumnMetadata(Field field, String columnName) {
        this(field, columnName, false, false);
    }

    public EntityColumnMetadata(Field field, String columnName, boolean id, boolean autoGenerated) {
        this.field = field;
        this.columnName = columnName;
        this.id = id;
        this.autoGenerated = autoGenerated;
    }

    public Field getField() {
        return field;
    }

    public String getColumnName() {
        return columnName;
    }

    public boolean isId() {
        return id;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
