
package org.neogroup.sparks.resources.processors;

import org.neogroup.sparks.resources.*;
import org.neogroup.sparks.resources.commands.ResourcesCommand;

import javax.sql.DataSource;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.sql.*;
import java.util.*;

public abstract class DataSourceResourceProcessor<R extends Resource> extends ResourceProcessor<R> {

    private final DataSource source;
    private ResourceTableMetadata resourceTableMetadata;

    public DataSourceResourceProcessor() {
        this.source = createDataSource();

        Type type = this.getClass().getGenericSuperclass();
        if(type instanceof ParameterizedType) {
            ParameterizedType parameterizedType = (ParameterizedType) type;
            Type[] fieldArgTypes = parameterizedType.getActualTypeArguments();
            Class<? extends R> resourceClass = (Class<? extends R>) fieldArgTypes[0];
            resourceTableMetadata = getResourceTableMetadata (resourceClass);
        }
    }

    protected DataSource getDataSource () {
        return source;
    }

    protected ResourceTableMetadata getResourceTableMetadata() {
        return resourceTableMetadata;
    }

    @Override
    protected R create(R resource, Map<String, Object> params) {

        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            int parameterIndex;
            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("INSERT INTO ");
            sql.append(resourceTableMetadata.getTableName());
            sql.append(" (");

            parameterIndex = 1;
            for (ResourceColumnMetadata columnMetadata : resourceTableMetadata.getColumnMetadatas()) {
                if (!columnMetadata.isAutoGenerated()) {
                    if (parameterIndex > 1) {
                        sql.append(",");
                    }
                    sql.append(columnMetadata.getColumnName());
                    parameterIndex++;
                }
            }
            sql.append(") VALUES (");
            parameterIndex = 1;
            for (ResourceColumnMetadata columnMetadata : resourceTableMetadata.getColumnMetadatas()) {
                if (!columnMetadata.isAutoGenerated()) {
                    if (parameterIndex > 1) {
                        sql.append(",");
                    }
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(resource));
                    parameterIndex++;
                }
            }
            sql.append(")");

            PreparedStatement statement = connection.prepareStatement(sql.toString(), Statement.RETURN_GENERATED_KEYS);

            parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            int affectedRows = statement.executeUpdate();

            if (affectedRows != 0) {
                parameterIndex = 1;
                try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                    for (ResourceColumnMetadata columnMetadata : resourceTableMetadata.getColumnMetadatas()) {
                        if (columnMetadata.isAutoGenerated()) {
                            if (generatedKeys.next()) {
                                columnMetadata.getField().set(resource, generatedKeys.getObject(parameterIndex++));
                            } else {
                                throw new SQLException("Expecting generated value");
                            }
                        }
                    }
                }
            }
        }
        catch (Exception ex) {
            throw new RuntimeException ("Error creating resource", ex);
        }
        return resource;
    }

    @Override
    protected R update(R resource, Map<String, Object> params) {

        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            int parameterIndex;
            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("UPDATE ");
            sql.append(resourceTableMetadata.getTableName());
            sql.append(" SET ");
            parameterIndex = 1;
            for (ResourceColumnMetadata columnMetadata : resourceTableMetadata.getColumnMetadatas()) {
                if (!columnMetadata.isId()) {
                    if (parameterIndex > 1) {
                        sql.append(",");
                    }
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(resource));
                    parameterIndex++;
                }
            }
            sql.append(" WHERE ");
            parameterIndex = 1;
            for (ResourceColumnMetadata columnMetadata : resourceTableMetadata.getColumnMetadatas()) {
                if (columnMetadata.isId()) {
                    if (parameterIndex > 1) {
                        sql.append(" AND ");
                    }
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(resource));
                    parameterIndex++;
                }
            }

            PreparedStatement statement = connection.prepareStatement(sql.toString());

            parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            int affectedRows = statement.executeUpdate();
        }
        catch (Exception ex) {
            throw new RuntimeException("Error updating resource", ex);
        }

        return resource;
    }

    @Override
    protected R delete(R resource, Map<String, Object> params) {

        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            int parameterIndex;
            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("DELETE FROM ");
            sql.append(resourceTableMetadata.getTableName());
            sql.append(" WHERE ");
            parameterIndex = 1;
            for (ResourceColumnMetadata columnMetadata : resourceTableMetadata.getColumnMetadatas()) {
                if (columnMetadata.isId()) {
                    if (parameterIndex > 1) {
                        sql.append(" AND ");
                    }
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(columnMetadata.getField().get(resource));
                    parameterIndex++;
                }
            }

            PreparedStatement statement = connection.prepareStatement(sql.toString());
            parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            int affectedRows = statement.executeUpdate();
        }
        catch (Exception ex) {
            throw new RuntimeException("Error deleting resource", ex);
        }

        return resource;
    }

    @Override
    protected List<R> retrieve(ResourceFilter filters, List<ResourceOrder> orders, Map<String, Object> params) {

        List<R> resources = new ArrayList<>();
        try {
            DataSource source = getDataSource();
            Connection connection = source.getConnection();

            List<Object> sqlParameters = new ArrayList<>();

            StringBuilder sql = new StringBuilder();
            sql.append("SELECT * FROM ");
            sql.append(resourceTableMetadata.getTableName());

            if (filters != null) {
                sql.append(" WHERE ");
                buildFilterSQL(filters, sql, sqlParameters);
            }

            if (orders != null) {
                sql.append(" ORDER BY ");
                Iterator<ResourceOrder> orderIterator = orders.iterator();
                while (orderIterator.hasNext()) {
                    ResourceOrder order = orderIterator.next();
                    ResourceColumnMetadata columnMetadata = resourceTableMetadata.getColumnMetadataByPropertyName(order.getProperty());
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" ");
                    switch (order.getDirection()) {
                        case ASC:
                            sql.append("ASC");
                            break;
                        case DESC:
                            sql.append("DESC");
                            break;
                    }
                    if (orderIterator.hasNext()) {
                        sql.append(",");
                    }
                }
            }

            if (params != null) {
                if (params.containsKey(ResourcesCommand.START_PARAMETER)) {
                    sql.append(" START ");
                    sql.append(params.get(ResourcesCommand.START_PARAMETER));
                }
                if (params.containsKey(ResourcesCommand.LIMIT_PARAMETER)) {
                    sql.append(" LIMIT ");
                    sql.append(params.get(ResourcesCommand.LIMIT_PARAMETER));
                }
            }

            PreparedStatement statement = connection.prepareStatement(sql.toString());
            int parameterIndex = 1;
            for (Object sqlParameter : sqlParameters) {
                statement.setObject(parameterIndex++, sqlParameter);
            }

            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                R resource = createResourceFromResultSet(resultSet);
                resources.add(resource);
            }
        }
        catch (Exception ex) {
            throw new RuntimeException("Error retrieving resources", ex);
        }

        return resources;
    }

    private void buildFilterSQL(ResourceFilter filter, StringBuilder sql, List<Object> sqlParameters) {

        if (filter instanceof ResourceFilterGroup) {
            ResourceFilterGroup resourceFilterGroup = (ResourceFilterGroup)filter;
            sql.append("(");
            Iterator<ResourceFilter> resourceFilterIterator = resourceFilterGroup.getFilters().iterator();
            while (resourceFilterIterator.hasNext()) {
                ResourceFilter childResourceFilter = resourceFilterIterator.next();
                buildFilterSQL(childResourceFilter, sql, sqlParameters);

                if (resourceFilterIterator.hasNext()) {
                    switch (resourceFilterGroup.getConnector()) {
                        case AND:
                            sql.append(" AND ");
                            break;
                        case OR:
                            sql.append(" OR ");
                            break;
                    }
                }
            }
            sql.append(")");
        }
        else if (filter instanceof ResourcePropertyFilter) {
            ResourcePropertyFilter resourcePropertyFilter = (ResourcePropertyFilter)filter;
            ResourceColumnMetadata columnMetadata = resourceTableMetadata.getColumnMetadataByPropertyName(resourcePropertyFilter.getProperty());
            switch (resourcePropertyFilter.getOperator()) {
                case ResourcePropertyOperator.EQUALS:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case ResourcePropertyOperator.DISTINCT:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("!=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case ResourcePropertyOperator.GREATER_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(">");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case ResourcePropertyOperator.GREATER_OR_EQUALS_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(">=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case ResourcePropertyOperator.LESS_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("<");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case ResourcePropertyOperator.LESS_OR_EQUALS_THAN:
                    sql.append(columnMetadata.getColumnName());
                    sql.append("<=");
                    sql.append("?");
                    sqlParameters.add(resourcePropertyFilter.getValue());
                    break;
                case ResourcePropertyOperator.CONTAINS:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" LIKE ");
                    sql.append("?");
                    sqlParameters.add("%" + resourcePropertyFilter.getValue() + "%");
                    break;
                case ResourcePropertyOperator.NOT_CONTAINS:
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" NOT LIKE ");
                    sql.append("?");
                    sqlParameters.add("%" + resourcePropertyFilter.getValue() + "%");
                    break;
                case ResourcePropertyOperator.IN: {
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" IN ");
                    sql.append("(");
                    Collection valueCollection = (Collection) resourcePropertyFilter.getValue();
                    Iterator valueCollectionIterator = valueCollection.iterator();
                    while (valueCollectionIterator.hasNext()) {
                        Object singleValue = valueCollectionIterator.next();
                        sql.append("?");
                        sqlParameters.add(singleValue);
                        if (valueCollectionIterator.hasNext()) {
                            sql.append(",");
                        }
                    }
                    sql.append(")");
                    break;
                }
                case ResourcePropertyOperator.NOT_IN: {
                    sql.append(columnMetadata.getColumnName());
                    sql.append(" NOT IN ");
                    sql.append("(");
                    Collection valueCollection = (Collection) resourcePropertyFilter.getValue();
                    Iterator valueCollectionIterator = valueCollection.iterator();
                    while (valueCollectionIterator.hasNext()) {
                        Object singleValue = valueCollectionIterator.next();
                        sql.append("?");
                        sqlParameters.add(singleValue);
                        if (valueCollectionIterator.hasNext()) {
                            sql.append(",");
                        }
                    }
                    sql.append(")");
                    break;
                }
            }
        }
    }

    protected ResourceTableMetadata getResourceTableMetadata (Class<? extends R> resourceClass) {
        return null;
    }

    protected R createResourceFromResultSet (ResultSet resultSet) {
        return null;
    }

    protected abstract DataSource createDataSource();
}
